# Nome do Workflow
name: Backend Pipeline - Hackathon

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
      name: Build
      runs-on: ubuntu-latest
      steps: 
        - name: Clone do Repositório
          uses: actions/checkout@v2

        - name: Login no Google Artifact Registry
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          run: | 
            echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
            cat key.json | docker login -u _json_key --password-stdin https://us-east4-docker.pkg.dev/

        - name: Build Image & Push
        env: 
          ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
        run: | 
          docker build -t ${{ secrets.ARTIFACT_REGISTRY_REPO }}/hack-aso-grupo-04-back:latest .
          docker push ${{ secrets.ARTIFACT_REGISTRY_REPO }}/hack-aso-grupo-04-back:latest

        - name: Show file
          run: cat App.py

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone do Repositório
        uses: actions/checkout@v2

      - name: Autenticação no Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy hack-aso-grupo-04-back no  Cloud Run
        id: deploy
        run: |-
          gcloud run deploy hack-aso-grupo-04-back \
            --quiet \
            --region  ${{ secrets.GOOGLE_REGION }} \
            --image ${{ secrets.ARTIFACT_REGISTRY }}/hack-aso-grupo-04-back:latest \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GOOGLE_PROJECT_ID }} \
            --format json